limupa/blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'

urlpatterns = [
    
]

limupa/limupa/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),

    path('master/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

limupa/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('product/<slug:product_slug>/', views.product_detail_view, name='product_detail'),
    path('shop/', views.ProductListView.as_view(), name='shop')
]

limupa/templates/index.html
{% extends 'wrapper.html' %} {% load static %} {% block content %}
<!-- Header Area End Here -->
<!-- Begin Slider With Category Menu Area -->
<div class="slider-with-banner">
  <div class="container">
    <div class="row">
      <!-- Begin Category Menu Area -->
      <div class="col-lg-3">
        <!--Category Menu Start-->
        <div class="category-menu">
          <div class="category-heading">
            <h2 class="categories-toggle"><span>categories</span></h2>
          </div>
          <div id="cate-toggle" class="category-menu-list">
            <ul>
              {% for category in categories %}
              <li><a href="{% url 'main:shop' %}?category={{ category.id }}">{{ category }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <!--Category Menu End-->
      </div>
      <!-- Category Menu Area End Here -->
      <!-- Begin Slider Area -->
      <div class="col-lg-9">
        <div class="slider-area pt-sm-30 pt-xs-30">
          <div class="slider-active owl-carousel">
            {% for banner in banners %}
            <div class="single-slide align-center-left animation-style-02 bg-4">
              <div class="slider-progress"></div>
              <div class="slider-content">
                <h5>{{ banner.subtitle }}</h5>
                <h2>{{ banner.title }}</h2>
                <h3>Starting at <span>{{ banner.text }}</span></h3>
                <div class="default-btn slide-btn">
                  <a class="links" href="#">Shopping Now</a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <!-- Slider Area End Here -->
    </div>
  </div>
</div>
<!-- Slider With Category Menu Area End Here -->
<!-- Begin Li's Static Banner Area -->
<div class="li-static-banner pt-20 pt-sm-30 pt-xs-30">
  <div class="container">
    <div class="row">
      {% for sub_banner in sub_banners %}
      <!-- Begin Single Banner Area -->
      <div class="col-lg-4 col-md-4">
        <div class="single-banner pb-xs-30">
          <a href="#">
            <img src="{{ sub_banner.image.url }}" alt="Banner" />
          </a>
        </div>
      </div>
      <!-- Single Banner Area End Here -->
      {% endfor %}
    </div>
  </div>
</div>
<!-- ////// -->
<br />
<br />
<section class="product-area li-laptop-product li-smart-phone-product-2 pb-50">
  <div class="container">
    <div class="row">
      <!-- Begin Li's Section Area -->
      <div class="col-lg-12">
        <div class="li-section-title">
          <h2>
            <span>Smartphone</span>
          </h2>
        </div>
        <div class="row">
          <div class="product-active owl-carousel">
            <div class="col-lg-12">
              {% for product in products %}
              <!-- single-product-wrap start -->
              <div class="single-product-wrap">
                <div class="product-image">
                  <a href="#">
                    <img
                      src="{{ product.poster.url }}"
                      alt="Li's Product Image"
                    />
                  </a>
                </div>
                <div class="product_desc">
                  <div class="product_desc_info">
                    <div class="product-review">
                      <h5 class="manufacturer">
                        <a href="#">{{ product.title }}</a>
                      </h5>
                      <div class="rating-box">
                        <ul class="rating">
                          <li>{{ product.rating_count }}/</li>
                          <li>
                            <i class="fa fa-star-o"></i>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <h4>
                      <a class="product_name" href="#"
                        >{{ product.category }}</a
                      >
                    </h4>
                    <div class="price-box">
                      <span class="new-price">${{ product.get_cost }}</span>
                      {% if product.discount %}
                      <s class="new-price">${{ product.cost }}</s>
                      {% endif %}
                    </div>
                  </div>
                  <div class="add-actions">
                    <ul class="add-actions-link">
                      <li class="add-cart active">
                        <a href="#">Add to cart</a>
                      </li>
                      <li>
                        <a class="links-details" href="#"
                          ><i class="fa fa-heart-o"></i
                        ></a>
                      </li>
                      <li>
                        <a href="#" title="quick view" class="quick-view-btn"
                          ><i class="fa fa-eye"></i
                        ></a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <!-- single-product-wrap end -->
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <!-- Li's Section Area End Here -->
    </div>
  </div>
</section>
<!-- Li's Smart Phone Product Area End Here -->
<!-- Begin Li's Static Home Area -->
<div class="li-static-home">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <!-- Begin Li's Static Home Image Area -->
        <div class="li-static-home-image"></div>
        <!-- Li's Static Home Image Area End Here -->
        <!-- Begin Li's Static Home Content Area -->
        <div class="li-static-home-content">
          <p>Sale Offer<span>-20% Off</span>This Week</p>
          <h2>Featured Product</h2>
          <h2>Meito Accessories 2018</h2>
          <p class="schedule">
            Starting at
            <span> $1209.00</span>
          </p>
          <div class="default-btn">
            <a href="shop-left-sidebar.html" class="links">Shopping Now</a>
          </div>
        </div>
        <!-- Li's Static Home Content Area End Here -->
      </div>
    </div>
  </div>
</div>
<!-- Li's Static Home Area End Here -->
<!-- Begin Li's Trending Product | Home V2 Area -->
<section
  class="product-area li-trending-product li-trending-product-2 pt-60 pb-45"
>
  <div class="container">
    <div class="row">
      <!-- Begin Li's Tab Menu Area -->
      <div class="col-lg-12">
        <div class="li-product-tab li-trending-product-tab">
          <h2>
            Trendding Products
          </h2>
        </div>
        <!-- Begin Li's Tab Menu Content Area -->
        <div class="row mt-50 mb-50">
          {% for trend in trendings %}
          <div class="col-md-3">
            <!-- single-product-wrap start -->
            <div class="single-product-wrap">
              <div class="product-image">
                <a href="#">
                  <img src="{{ trend.poster.url }}" alt="Li's Product Image" />
                </a>
              </div>
              <div class="product_desc">
                <div class="product_desc_info">
                  <div class="product-review">
                    <h5 class="manufacturer">
                      <a href="#">{{ trend.title }}</a>
                    </h5>
                    <div class="rating-box">
                      <ul class="rating">
                        <li>{{ trend.rating_count }}/</li>
                        <li><i class="fa fa-star-o"></i></li>
                      </ul>
                    </div>
                  </div>
                  <h4>
                    <a class="product_name" href="#">{{ trend.category }}</a>
                  </h4>
                  <div class="price-box">
                    <span class="new-price">${{ trend.get_cost }}</span>
                    {% if trend.discount %}
                    <s class="new-price">${{ trend.cost }}</s>
                    {% endif %}
                  </div>
                </div>
                <div class="add-actions">
                  <ul class="add-actions-link">
                    <li class="add-cart active"><a href="#">Add to cart</a></li>
                    <li>
                      <a class="links-details" href="wishlist.html"
                        ><i class="fa fa-heart-o"></i
                      ></a>
                    </li>
                    <li>
                      <a
                        href="#"
                        title="quick view"
                        class="quick-view-btn"
                        data-toggle="modal"
                        data-target="#exampleModalCenter"
                        ><i class="fa fa-eye"></i
                      ></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- single-product-wrap end -->
          </div>
          {% endfor %}
        </div>
        <!-- Tab Menu Content Area End Here -->
      </div>
      <!-- Tab Menu Area End Here -->
    </div>
  </div>
</section>
<!-- Li's Trending Product | Home V2 Area End Here -->
<!-- Begin Footer Area -->
{% endblock content %}

limupa/templates/shop.html
{% extends 'wrapper.html' %}
{% load get_request_list %}
{% block content %}
<style>
    .color_label {
        display: flex;
    }
    .color_label input[type=checkbox] {
        display: none;
    }
    .color_span {
        position: relative;
    }
    .color_span::after {
        content: "";
        width: 10px;
        height: 10px;
        background: #545954;
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: -1;
    }
    .color_label > input[type="checkbox"]:checked ~ .color_span::after {
        z-index: 11111 !important
    }
</style>
<!-- Header Area End Here -->
<!-- Begin Li's Breadcrumb Area -->
<div class="breadcrumb-area">
  <div class="container">
    <div class="breadcrumb-content">
      <ul>
        <li><a href="/">Home</a></li>
        <li class="active">Shop Products</li>
      </ul>
    </div>
  </div>
</div>
<!-- Li's Breadcrumb Area End Here -->
<!-- Begin Li's Content Wraper Area -->
<form class="content-wraper pt-60 pb-60 pt-sm-30 pt-xs-30">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 order-2 order-lg-1 order-sm-1">
        <!-- shop-top-bar start -->
        <div class="shop-top-bar mt-30">
          <!-- product-select-box start -->
          <div class="product-select-box">
            <div class="product-short">
              <p>Sort By:</p>
              <select name="sort" class="nice-select">
                <option value="">Relevance</option>
                <option value="cost">Price (Low &gt; High)</option>
                <option value="-cost">Price (High &gt; Low)</option>
              </select>
            </div>
          </div>
          <div>
            <button class="btn btn-outline-dark">Filter</button>
          </div>
          <!-- product-select-box end -->
        </div>
        <!-- shop-top-bar end -->
        <!-- shop-products-wrapper start -->
        <div class="shop-products-wrapper">
          <div class="tab-content">
            <div
              id="grid-view"
              class="tab-pane fade active show"
              role="tabpanel"
            >
              <div class="product-area shop-product-area">
                <div class="row">
                  {% for product in products %}
                  <div class="col-lg-4 col-md-4 col-sm-6 mt-40">
                    <!-- single-product-wrap start -->
                    <div class="single-product-wrap">
                      <div class="product-image">
                        <a href="{% url 'main:product_detail' product.slug %}">
                          <img
                            src="{{ product.poster.url }}"
                            alt="Image Not Found"
                          />
                        </a>
                      </div>
                      <div class="product_desc">
                        <div class="product_desc_info">
                          <div class="product-review">
                            <h5 class="manufacturer">
                              <a
                                href="{% url 'main:product_detail' product.slug %}"
                                >{{ product.title }}</a
                              >
                            </h5>
                            <div class="rating-box">
                              <ul class="rating">
                                <li>{{ product.get_rating }} /</li>
                                <li><i class="fa fa-star-o"></i></li>
                              </ul>
                            </div>
                          </div>
                          <h4>
                            <a class="product_name" href="#"
                              >{{ product.category }}</a
                            >
                          </h4>
                          <div class="price-box">
                            <span class="new-price"
                              >${{ product.get_cost }}</span
                            >
                            {% if product.discount %}
                            <s class="new-price">${{ product.cost }}</s>
                            {% endif %}
                          </div>
                        </div>
                        <div class="add-actions">
                          <ul class="add-actions-link">
                            <li class="add-cart active">
                              <a href="#">Add to cart</a>
                            </li>
                            <li>
                              <a
                                href="{% url 'main:product_detail' product.slug %}"
                                title="quick view"
                                class="quick-view-btn"
                                ><i class="fa fa-eye"></i
                              ></a>
                            </li>
                            <li>
                              <a class="links-details" href="#    "
                                ><i class="fa fa-heart-o"></i
                              ></a>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <!-- single-product-wrap end -->
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="paginatoin-area">
              <div class="row">
                <div class="col-lg-6 col-md-6">
                  <ul class="pagination-box pt-xs-20 pb-xs-15">
                    {% if page_obj.has_previous %}
                    <li>
                      <a href="?page={{ page_obj.previous_page_number }}" class="Previous"
                        ><i class="fa fa-chevron-left"></i> Previous</a
                      >
                    </li>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <li>
                      <a href="?page={{ page_obj.next_page_number }}" class="Next">
                        Next <i class="fa fa-chevron-right"></i
                      ></a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- shop-products-wrapper end -->
      </div>
      <div class="col-lg-3 order-1 order-lg-2">
        <!--sidebar-categores-box start  -->
        <div class="sidebar-categores-box">
          <div class="sidebar-title">
            <h2>Filter By</h2>
          </div>
          <!-- btn-clear-all start -->
          <button class="btn-clear-all mb-sm-30 mb-xs-30">Clear all</button>
          <!-- btn-clear-all end -->
          <!-- filter-sub-area start -->
          <div class="filter-sub-area">
            <h5 class="filter-sub-titel">Brand</h5>
            <div class="categori-checkbox">
              <ul>
                {% for brand in brands %}
                <li>
                  <label for="brand_{{ brand.id }}">
                    {% if brand.id|stringformat:"i" in request.GET|get_item:"brand" %}
                    <input
                      id="brand_{{ brand.id }}"
                      type="checkbox"
                      name="brand"
                      value="{{ brand.id }}"
                      checked
                      />
                      {% else %}
                      <input
                      id="brand_{{ brand.id }}"
                      type="checkbox"
                      name="brand"
                      value="{{ brand.id }}"
                      />
                    {% endif %}
                    <span>{{ brand.title }}</span>
                  </label>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <!-- filter-sub-area end -->
          <!-- filter-sub-area start -->
          <div class="filter-sub-area pt-sm-10 pt-xs-10">
            <h5 class="filter-sub-titel">Categories</h5>
            <div class="categori-checkbox">
              <ul>
                {% for category in categories %}
                <li>
                  <label for="category_{{ category.id }}">
                    {% if category.id|stringformat:"i" in request.GET|get_item:"category" %}
                    <input
                      id="category_{{ category.id }}"
                      type="checkbox"
                      name="category"
                      checked
                      value="{{ category.id }}"
                    />
                    {% else %}
                    <input
                      id="category_{{ category.id }}"
                      type="checkbox"
                      name="category"
                      value="{{ category.id }}"
                    />
                    {% endif %}
                    <span>{{ category.title }}</span>
                  </label>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <!-- filter-sub-area end -->
          <!-- filter-sub-area start -->
          <div class="filter-sub-area pt-sm-10 pt-xs-10">
            <h5 class="filter-sub-titel">Color</h5>
            <div class="color-categoriy">
              <ul>
                {% for color in colors %}
                <li>
                  <label class="color_label" for="color_{{ color.id }}">
                    
                    <span class="color_span"
                      style="background-color: {{ color.color_code }}"
                    ></span
                    ><a>{{ color.title }}</a>
                    <input
                      type="checkbox"
                      name="color"
                      value="{{ color.id }}"
                      id="color_{{ color.id }}"
                    />
                  </label>
                </li>
                {% endfor %}
              </ul>
            </div>
            <button class="btn btn-outline-dark">Filter</button>
          </div>
          <!-- filter-sub-area end -->
          <!-- filter-sub-area start -->
          <!-- filter-sub-area end -->
        </div>
        <!--sidebar-categores-box end  -->
        <!-- category-sub-menu start -->
        <div class="sidebar-categores-box mb-sm-0 mb-xs-0">
          <div class="category-tags">
            <ul>
              {% for tag in tags %}
              <li><a href="#">{{ tag.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
          <!-- category-sub-menu end -->
        </div>
      </div>
    </div>
  </div>
</form>
<!-- Content Wraper Area End Here -->
<!-- Begin Footer Area -->
{% endblock content %}